### ISSUE TITLE
[Dialog] React SSR warning when defaultOpen is used without Dialog.Portal

### ISSUE THREAD

**Issue by jdeblasse** [radix-ui/primitives#1182]
### Current Behavior

When using Dialog with either defaultOpen or open set to true and when using content without a Portal, React throws a SSR warning.

```tsx
<Dialog.Root defaultOpen>
  <Dialog.Content>
    <Dialog.Title>Title</Dialog.Title>
    <Dialog.Description>Description</Dialog.Description>
    <Dialog.Close>X</Dialog.Close>
  </Dialog.Content>
</Dialog.Root>
```

### Expected behavior

When composing Dialog without a Portal, defaultOpen and open=true should not throw a warning.

### Reproducible example

Quickest way is using Create NextApp and pasting the above code in pages/index.js

```sh
yarn create next-app radix-dialog-test
cd radix-dialog-test
yarn add @radix-ui/react-dialog
yarn dev
```

### Suggested solution

I'm not completely sure. It seems that somewhere in the composition chain there needs to be your custom `useLayoutEffect` hook where there is only the standard `useEffect` however I am unsure where. Perhaps DismissableLayer.

### Your environment

| Software                   | Name(s)    | Version |
| ----------------       | -------       | ------- |
| Radix Package(s)     |     Dialog    |  0.1.5   |
| React                         |    n/a          |    17.0.2     |
| Browser                     |    Chrome  |    98.0.4758.102     |
| Assistive tech           |                    |         |
| Node                         |    n/a           |    v16.13.1     |
| npm/yarn                  |    yarn         |  tested on yarn 1.x and yarn 3.x  |
| Operating System    |   osx           |  12.2.1       |

**Comment by benoitgrelard** [comment]
Hi @jdeblasse,

Could you create a sandbox so we can take a look?

Thanks 🙏

**Comment by jdeblasse** [comment]
@benoitgrelard Looks like a new version of Dialog was released 0.1.6 since my creating this issue. I've tested both in a local sandbox just now that I intended to publish for you however the bug no longer exists in 0.1.6. I tested 01.5 to make sure and it is indeed present there still. So, 0.1.6 seems to have solved this issue. I think we are safe to close. I can still provide the sandbox if you'd like?

**Comment by benoitgrelard** [comment]
I guess I'm curious what the error was about yes so if you can still provide a sandbox I'd like to take a look.
But yes, I will close the issue if it's resolved for you.

🙏

**Comment by jdeblasse** [comment]
Here you go: https://github.com/jdeblasse/radix-dialog-sandbox

Run locally with `yarn dev`, navigate to http://localhost:3000 and check your terminal output. Error pasted below as well:

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dismissable-layer/dist/index.js:1:1070
    at r (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-context/dist/index.js:1:613)
    at r (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dismissable-layer/dist/index.js:1:2967)
    at r (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-context/dist/index.js:1:613)
    at r (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dismissable-layer/dist/index.js:1:2967)
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dismissable-layer/dist/index.js:1:822
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-slot/dist/index.js:1:705
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-slot/dist/index.js:1:370
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-primitive/dist/index.js:1:450
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-focus-scope/dist/index.js:1:509
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dialog/dist/index.js:1:4328
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dialog/dist/index.js:1:3083
    at o (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-presence/dist/index.js:1:329)
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dialog/dist/index.js:1:2775
    at s (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-context/dist/index.js:1:1239)
    at h (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dialog/dist/index.js:1:1100)
    at main
    at div
    at Home
    at MyApp (webpack-internal:///./pages/_app.js:11:18)
    at StyleRegistry (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/styled-jsx/dist/index/index.js:671:34)
    at AppContainer (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/next/dist/server/render.js:415:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/next/dist/server/render.js:447:57)
    at div
    at Body (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/next/dist/server/render.js:715:21)
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dismissable-layer/dist/index.js:1:1070
    at r (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-context/dist/index.js:1:613)
    at r (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dismissable-layer/dist/index.js:1:2967)
    at r (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-context/dist/index.js:1:613)
    at r (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dismissable-layer/dist/index.js:1:2967)
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dismissable-layer/dist/index.js:1:822
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-slot/dist/index.js:1:705
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-slot/dist/index.js:1:370
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-primitive/dist/index.js:1:450
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-focus-scope/dist/index.js:1:509
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dialog/dist/index.js:1:4328
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dialog/dist/index.js:1:3083
    at o (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-presence/dist/index.js:1:329)
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dialog/dist/index.js:1:2775
    at s (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-context/dist/index.js:1:1239)
    at h (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dialog/dist/index.js:1:1100)
    at main
    at div
    at Home
    at MyApp (webpack-internal:///./pages/_app.js:11:18)
    at StyleRegistry (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/styled-jsx/dist/index/index.js:671:34)
    at AppContainer (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/next/dist/server/render.js:415:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/next/dist/server/render.js:447:57)
    at div
    at Body (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/next/dist/server/render.js:715:21)
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dismissable-layer/dist/index.js:1:1070
    at r (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-context/dist/index.js:1:613)
    at r (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dismissable-layer/dist/index.js:1:2967)
    at r (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-context/dist/index.js:1:613)
    at r (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dismissable-layer/dist/index.js:1:2967)
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dismissable-layer/dist/index.js:1:822
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-slot/dist/index.js:1:705
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-slot/dist/index.js:1:370
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-primitive/dist/index.js:1:450
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-focus-scope/dist/index.js:1:509
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dialog/dist/index.js:1:4328
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dialog/dist/index.js:1:3083
    at o (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-presence/dist/index.js:1:329)
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dialog/dist/index.js:1:2775
    at s (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-context/dist/index.js:1:1239)
    at h (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dialog/dist/index.js:1:1100)
    at main
    at div
    at Home
    at MyApp (webpack-internal:///./pages/_app.js:11:18)
    at StyleRegistry (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/styled-jsx/dist/index/index.js:671:34)
    at AppContainer (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/next/dist/server/render.js:415:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/next/dist/server/render.js:447:57)
    at div
    at Body (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/next/dist/server/render.js:715:21)
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dismissable-layer/dist/index.js:1:1070
    at r (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-context/dist/index.js:1:613)
    at r (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dismissable-layer/dist/index.js:1:2967)
    at r (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-context/dist/index.js:1:613)
    at r (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dismissable-layer/dist/index.js:1:2967)
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dismissable-layer/dist/index.js:1:822
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-slot/dist/index.js:1:705
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-slot/dist/index.js:1:370
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-primitive/dist/index.js:1:450
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-focus-scope/dist/index.js:1:509
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dialog/dist/index.js:1:4328
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dialog/dist/index.js:1:3083
    at o (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-presence/dist/index.js:1:329)
    at /Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dialog/dist/index.js:1:2775
    at s (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-context/dist/index.js:1:1239)
    at h (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/@radix-ui/react-dialog/dist/index.js:1:1100)
    at main
    at div
    at Home
    at MyApp (webpack-internal:///./pages/_app.js:11:18)
    at StyleRegistry (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/styled-jsx/dist/index/index.js:671:34)
    at AppContainer (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/next/dist/server/render.js:415:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/next/dist/server/render.js:447:57)
    at div
    at Body (/Users/shu-sin/Sites/atlanticrecords/radix-dialog-sandbox/node_modules/next/dist/server/render.js:715:21)
```

**Comment by jdeblasse** [comment]
Thanks for the feedback and explanation. I'm going to remove the sandbox now. Thanks again.
