### ISSUE TITLE
[Dropdown Menu] On NextJS, `userEvent.click` on `button`  during `Jest` / `React Testing Library` tests doesn't seem to open menu

### ISSUE THREAD

**Issue by ItzaMi** [radix-ui/primitives#1608]
### Current Behavior

From my understanding, it seems that trying to trigger a `click` on the `DropdownMenu.Trigger` on the tests isn't actually working.

Running the following test
```jsx
test('Dropdown trigger gets clicked and menu opens', async () => {
  render(<Dropdown
    chosenOption={undefined}
    label={label}
    options={dropdownOptions}
    placeholder={placeholder}
    setOption={() => jest.fn()}
  />)

  userEvent.click(screen.getByRole('button'))

  expect(await screen.findByText('Option 1')).toBeInTheDocument()
})
```
Gets me the following errors on the terminal

```shell
 TypeError: _observer.disconnect is not a function
 
  Error: Uncaught [TypeError: _observer.disconnect is not a function]
        at reportException (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at innerInvokeEventListeners (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:343:9)
        at invokeEventListeners (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:276:3)
        at HTMLUnknownElementImpl._dispatch (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:223:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
        at HTMLUnknownElement.dispatchEvent (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
        at Object.invokeGuardedCallbackDev (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:4213:16)
        at invokeGuardedCallback (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:4277:31)
        at reportUncaughtErrorInDEV (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:22838:5)
        at captureCommitPhaseError (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:27126:5) {
      detail: TypeError: _observer.disconnect is not a function
          at Object.current (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/@floating-ui/dom/dist/floating-ui.dom.umd.js:583:59)
          at /Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/@floating-ui/react-dom/dist/floating-ui.react-dom.js:168:20
          at /Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/@floating-ui/react-dom/dist/floating-ui.react-dom.js:187:7
          at safelyDetachRef (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:22913:20)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24003:11)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24170:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24170:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24170:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24170:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24170:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24170:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24170:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5)
          at commitDeletionEffectsOnFiber (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:24118:9)
          at recursivelyTraverseDeletionEffects (/Users/ruisousa/Desktop/Dev/X/dashboard/node_modules/react-dom/cjs/react-dom.development.js:23989:5),
      type: 'unhandled exception'
    }

      at VirtualConsole.<anonymous> (node_modules/jest-environment-jsdom/build/index.js:70:23)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:343:9)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:276:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:223:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
```

I previously had this issue using CRA and got a solution in [this issue](https://github.com/radix-ui/primitives/issues/1220) but now I'm working with NextJS and I expected for the issue to be the same.

### Expected behavior

As with the CRA tests, I expected to target the `button`, click it, and be able to find the `menu` during the tests

### Reproducible example

https://codesandbox.io/s/dropdown-menu-tests-gbyng1?file=/components/Dropdown/dropdown.test.tsx

### Suggested solution

No idea on what might be happening

### Additional context

Nothing to add here

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    `@radix-ui/react-dropdown-menu`     |     1.0.0    |
| React            | n/a     |    18.2.0     |
| Browser          |    -     |    -     |
| Assistive tech   |    -    |    -     |
| Node             | n/a     |     v18.0.0    |
| npm/yarn         |     yarn    |     1.22.19    |
| Operating System |    MacOS Montery     |     12.3.1    |

**Comment by andy-hook** [comment]
Hi @ItzaMi ,

This is due to a combination of changes, one is that `user-event` v14 is shipped in the [latest next/jest starter](https://github.com/vercel/next.js/tree/canary/examples/with-jest) and Radix [moved to `floating-ui`](https://github.com/radix-ui/primitives/pull/1531) in the v1 release.

Providing you're using the next starter and Radix v1, here are the modifications you need to make:

Ensure your tests conform to [the `user-event` v14 api](https://testing-library.com/docs/user-event/intro#writing-tests-with-userevent), specifically the recommendation for being explicit and calling `userEvent.setup()`, it looks like this is handled internally as well (given your example test) but I'm adding it below for completeness:

```jsx
test("Dropdown trigger gets clicked and menu opens", async() => {
  const user = userEvent.setup();

  render(
    <Dropdown
      chosenOption={undefined}
      label={label}
      options={dropdownOptions}
      placeholder={placeholder}
      setOption={() => jest.fn()}
    />
  );

  await user.click(screen.getByRole("button"));

  expect(screen.getByRole("menu")).toBeInTheDocument();
});
```

The main problem in your case though is that the `ResizeObserver` mock has omitted the `disconnect` method, this is now required by `floating-ui` so adding that to the mock should fix your error.

```jsx
const createResizeObserver = () => {
  return (global.ResizeObserver = class ResizeObserver {
    [x: string]: any;
    constructor(cb: any) {
      this.cb = cb;
    }
    observe() {
      this.cb([{ borderBoxSize: { inlineSize: 0, blockSize: 0 } }]);
    }
    unobserve() {}
    disconnect() {}
  } as any);
};

export default createResizeObserver;
```

I have trouble with sandboxed `next` environments on CSB so I hope this explanation helps in place.

I'm going to close this now as I've tested this locally and seems to work well, please follow up if you still have issues though.

**Comment by ItzaMi** [comment]
Thank you, @andy-hook . You saved me once again with the clutch 😄
Indeed I didn't have to setup the `userEvent` and the following sufficed!

```javascript
test('Dropdown trigger gets clicked and menu opens', async () => {
  render(regularDropdown)

  await userEvent.click(screen.getByRole('button'))

  expect(screen.getByRole('menu')).toBeInTheDocument()
})
```

**Comment by ItzaMi** [comment]
@andy-hook , based on this implementation, how could I also test the click on a `menuitem`?

I'm trying to do the following
```javascript
test('Dropdown menu opens and able to pick an option', async () => {
  render(regularDropdown)

  await userEvent.click(screen.getByRole('button'))

  expect(screen.getByRole('menu')).toBeInTheDocument()

  expect(
    await screen.getByRole('menuitem', { name: 'Option 1' })
  ).toBeInTheDocument()

  fireEvent.click(screen.getByRole('menuitem', { name: 'Option 1' }))

  expect(jest.fn()).toHaveBeenCalledTimes(1)
})
```

But I'm always getting
```
Expected number of calls: 1
Received number of calls: 0
```

**Comment by andy-hook** [comment]
@ItzaMi Why do you need to test this core behaviour? really it's the responsibility of the library to ensure these basic interactions function and are tested.

In terms of your question though, you need to pass your spy to the component first before jest can assert whether it's be called correctly, an oversimplification being:

```js
const handleInteraction = jest.fn()

// Somewhere in your render
<MenuItem onClick={handleInteraction} />

// Later in the test
fireEvent.click(screen.getByRole('menuitem'))

expect(handleInteraction).toHaveBeenCalledTimes(1)
```

**Comment by ItzaMi** [comment]
@andy-hook , honestly, it's just for a matter of coverage. Presently the only line not tested within my component is the `onSelect` (or so does the coverage complains of), hence why I would like to test it (as you can see, missing the tests for the `onCloseAutoFocus` and `OnSelect`)
<img width="509" alt="Screenshot 2022-08-17 at 11 27 20" src="https://user-images.githubusercontent.com/30603437/185096900-38ece0d7-fdd1-4492-834c-6d7af1fdb324.png">
![Screenshot 2022-08-17 at 11 27 36](https://user-images.githubusercontent.com/30603437/185096957-d22a2cdb-8438-4612-8631-5619a6df32f4.png)

I was able to test it on previous project but can't seem to do it now with the `1.0`

The spy should be already be set via
```javascript
const regularDropdown = (
  <Dropdown
    chosenOption={undefined}
    label={label}
    options={dropdownOptions}
    placeholder={placeholder}
    setOption={() => jest.fn()}
  />
)
```

And on my actual component
```javascript
interface Props {
  chosenOption?: DropdownOptionProps
  errorMessage?: string
  label: string
  options: DropdownOptionProps[] | undefined
  placeholder: string
  setOption: (e: DropdownOptionProps) => void
}

const Dropdown: FC<Props> = ({
  chosenOption,
  errorMessage,
  label,
  options,
  placeholder,
  setOption,
}) => {
  [...]
  {options &&
    options.map((option, i) => {
      return (
        <DropdownMenu.Item onSelect={() => setOption(option)}>
      [...]
```

**Comment by benoitgrelard** [comment]
> `onSelect={() => setOption(option)}`

Seeing this makes me wonder if you're trying to build a select using `DropdownMenu`. They are very different semantically / accessibility-wise. We have a `Select` primitive for this.

**Comment by ItzaMi** [comment]
> > `onSelect={() => setOption(option)}`
> 
> Seeing this makes me wonder if you're trying to build a select using `DropdownMenu`. They are very different semantically / accessibility-wise. We have a `Select` primitive for this.

Hmm, now that you mention it, I am indeed using `DropdownMenu` for a `Select`. I completely missed the existence of `Select`
