### ISSUE TITLE
import error: 'dispatchDiscreteCustomEvent' is not exported from '@radix-ui/react-primitive' After upgrading

### ISSUE THREAD

**Issue by softmarshmallow** [radix-ui/primitives#1809]
```


../node_modules/@radix-ui/react-context-menu/dist/index.module.js
--
15:21:47.446 | Attempted import error: 'createContextScope' is not exported from '@radix-ui/react-context' (imported as '$3TiJz$createContextScope').
15:21:47.446 |  
15:21:47.446 | Import trace for requested module:
15:21:47.446 | ../node_modules/@radix-ui/react-context-menu/dist/index.module.js
15:21:47.446 | ../editor-packages/editor-preview-pip/lib/context-menu.tsx
15:21:47.446 | ../editor-packages/editor-preview-pip/lib/index.ts
15:21:47.446 | ../editor-packages/editor-preview-pip/index.ts
15:21:47.447 |  
15:21:47.447 | ../node_modules/@radix-ui/react-context-menu/node_modules/@radix-ui/react-dismissable-layer/dist/index.module.js
15:21:47.447 | Attempted import error: 'dispatchDiscreteCustomEvent' is not exported from '@radix-ui/react-primitive' (imported as '$kqwpH$dispatchDiscreteCustomEvent').
15:21:47.447 |  
15:21:47.447 | Import trace for requested module:
15:21:47.448 | ../node_modules/@radix-ui/react-context-menu/node_modules/@radix-ui/react-dismissable-layer/dist/index.module.js
15:21:47.448 | ../node_modules/@radix-ui/react-context-menu/node_modules/@radix-ui/react-menu/dist/index.module.js
15:21:47.448 | ../node_modules/@radix-ui/react-context-menu/dist/index.module.js
15:21:47.448 | ../editor-packages/editor-preview-pip/lib/context-menu.tsx
15:21:47.448 | ../editor-packages/editor-preview-pip/lib/index.ts
15:21:47.448 | ../editor-packages/editor-preview-pip/index.ts
15:21:47.448 |  
15:21:47.449 | ../node_modules/@radix-ui/react-context-menu/node_modules/@radix-ui/react-menu/dist/index.module.js
15:21:47.449 | Attempted import error: 'createContextScope' is not exported from '@radix-ui/react-context' (imported as '$epM9y$createContextScope').
15:21:47.449 |  
15:21:47.449 | Import trace for requested module:
15:21:47.449 | ../node_modules/@radix-ui/react-context-menu/node_modules/@radix-ui/react-menu/dist/index.module.js
15:21:47.449 | ../node_modules/@radix-ui/react-context-menu/dist/index.module.js
15:21:47.449 | ../editor-packages/editor-preview-pip/lib/context-menu.tsx
15:21:47.449 | ../editor-packages/editor-preview-pip/lib/index.ts
15:21:47.449 | ../editor-packages/editor-preview-pip/index.ts
15:21:47.450 |  
15:21:47.450 | ../node_modules/@radix-ui/react-context-menu/node_modules/@radix-ui/react-menu/dist/index.module.js
15:21:47.450 | Attempted import error: 'createPopperScope' is not exported from '@radix-ui/react-popper' (imported as '$epM9y$createPopperScope').
15:21:47.450 |  
15:21:47.450 | Import trace for requested module:
15:21:47.450 | ../node_modules/@radix-ui/react-context-menu/node_modules/@radix-ui/react-menu/dist/index.module.js
15:21:47.450 | ../node_modules/@radix-ui/react-context-menu/dist/index.module.js
15:21:47.450 | ../editor-packages/editor-preview-pip/lib/context-menu.tsx
15:21:47.450 | ../editor-packages/editor-preview-pip/lib/index.ts
15:21:47.451 | ../editor-packages/editor-preview-pip/index.ts
15:21:47.451 |  
15:21:47.451 | ../node_modules/@radix-ui/react-context-menu/node_modules/@radix-ui/react-menu/dist/index.module.js
15:21:47.451 | Attempted import error: 'createRovingFocusGroupScope' is not exported from '@radix-ui/react-roving-focus' (imported as '$epM9y$createRovingFocusGroupScope').
15:21:47.451 |  
15:21:47.451 | Import trace for requested module:
15:21:47.451 | ../node_modules/@radix-ui/react-context-menu/node_modules/@radix-ui/react-menu/dist/index.module.js
15:21:47.451 | ../node_modules/@radix-ui/react-context-menu/dist/index.module.js
15:21:47.451 | ../editor-packages/editor-preview-pip/lib/context-menu.tsx
15:21:47.451 | ../editor-packages/editor-preview-pip/lib/index.ts
15:21:47.452 | ../editor-packages/editor-preview-pip/index.ts
15:21:47.452 |  
15:21:47.452 | ../node_modules/@radix-ui/react-context-menu/node_modules/@radix-ui/react-menu/dist/index.module.js
15:21:47.452 | Attempted import error: 'createPopperScope' is not exported from '@radix-ui/react-popper' (imported as '$epM9y$createPopperScope').
15:21:47.452 |  
15:21:47.452 | Import trace for requested module:
15:21:47.452 | ../node_modules/@radix-ui/react-context-menu/node_modules/@radix-ui/react-menu/dist/index.module.js
15:21:47.452 | ../node_modules/@radix-ui/react-context-menu/dist/index.module.js
15:21:47.452 | ../editor-packages/editor-preview-pip/lib/context-menu.tsx
15:21:47.452 | ../editor-packages/editor-preview-pip/lib/index.ts
15:21:47.453 | ../editor-packages/editor-preview-pip/index.ts
15:21:47.453 |  
15:21:47.453 | ../node_modules/@radix-ui/react-context-menu/node_modules/@radix-ui/react-menu/dist/index.module.js
15:21:47.453 | Attempted import error: 'createRovingFocusGroupScope' is not exported from '@radix-ui/react-roving-focus' (imported as '$epM9y$createRovingFocusGroupScope').
15:21:47.453 |  
15:21:47.453 | Import trace for requested module:
15:21:47.453 | ../node_modules/@radix-ui/react-context-menu/node_modules/@radix-ui/react-menu/dist/index.module.js
15:21:47.453 | ../node_modules/@radix-ui/react-context-menu/dist/index.module.js
15:21:47.453 | ../editor-packages/editor-preview-pip/lib/context-menu.tsx
15:21:47.453 | ../editor-packages/editor-preview-pip/lib/index.ts
15:21:47.454 | ../editor-packages/editor-preview-pip/index.ts
15:21:47.454 |  
15:21:47.454 | ../node_modules/@radix-ui/react-context-menu/node_modules/@radix-ui/react-menu/dist/index.module.js
15:21:47.454 | Attempted import error: 'dispatchDiscreteCustomEvent' is not exported from '@radix-ui/react-primitive' (imported as '$epM9y$dispatchDiscreteCustomEvent').
15:21:47.455 |  
15:21:47.455 | Import trace for requested module:
15:21:47.456 | ../node_modules/@radix-ui/react-context-menu/node_modules/@radix-ui/react-menu/dist/index.module.js
15:21:47.456 | ../node_modules/@radix-ui/react-context-menu/dist/index.module.js
15:21:47.456 | ../editor-packages/editor-preview-pip/lib/context-menu.tsx
15:21:47.456 | ../editor-packages/editor-preview-pip/lib/index.ts
15:21:47.456 | ../editor-packages/editor-preview-pip/index.ts
15:21:47.456 |  
15:21:47.456 | ../node_modules/dart-style/index.js
15:21:47.456 | Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
15:21:47.456 |  
15:21:47.456 | Import trace for requested module:
15:21:47.457 | ../node_modules/dart-style/index.js
15:21:47.457 | ../editor-packages/editor-services-prettier/index.ts
15:21:47.457 | ./components/code-editor/monaco.tsx
15:21:47.457 | ./components/code-editor/index.ts
15:21:47.457 |  
15:21:47.458 | info  - Collecting page data...
15:21:49.209 | TypeError: $cnSS2$radixuireactcontext.createContextScope is not a function or its return value is not iterable
15:21:49.211 | at Object.<anonymous> (/vercel/path0/node_modules/@radix-ui/react-context-menu/node_modules/@radix-ui/react-menu/dist/index.js:124:121)
15:21:49.211 | at Module._compile (node:internal/modules/cjs/loader:1155:14)
15:21:49.211 | at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
15:21:49.211 | at Module.load (node:internal/modules/cjs/loader:1033:32)
15:21:49.212 | at Function.Module._load (node:internal/modules/cjs/loader:868:12)
15:21:49.212 | at Module.require (node:internal/modules/cjs/loader:1057:19)
15:21:49.212 | at require (node:internal/modules/cjs/helpers:103:18)
15:21:49.212 | at Object.<anonymous> (/vercel/path0/node_modules/@radix-ui/react-context-menu/dist/index.js:6:31)
15:21:49.212 | at Module._compile (node:internal/modules/cjs/loader:1155:14)
15:21:49.212 | at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
15:21:49.219 |  
15:21:49.219 | > Build error occurred
15:21:49.226 | Error: Failed to collect page data for /_development/editor-canvas
15:21:49.226 | at /vercel/path0/node_modules/next/dist/build/utils.js:916:15
15:21:49.227 | at processTicksAndRejections (node:internal/process/task_queues:96:5) {
15:21:49.227 | type: 'Error'
15:21:49.227 | }
15:21:49.482 | error Command failed with exit code 1.
15:21:49.482 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
15:21:49.507 | Error: Command "yarn run build" exited with 1
```

The error seems quite random, and there are lot of radix-ui dependencies, so I'm skipping with the details. For now I am reverting to older version, but let me know if this rings a bell :)

Thank you

**Comment by pedromcunha** [comment]
Running into this issue as well, had to downgrade to v0.1.6. It's unfortunate because I need the latest version for react 18.0

**Comment by benoitgrelard** [comment]
I would be very surprised if this was an issue on our side given that we are using all the primitives (and many other people too) without any issues.

Are you able to replicate this issue reliably in a sandbox?

**Comment by pedromcunha** [comment]
Seems to be working now on version 2.0.1 of the dropdown menu.
