### ISSUE TITLE
[Tabs] Unable to switch from tabpanel to another with @testing-library/react

### ISSUE THREAD

**Issue by silversonicaxel** [radix-ui/primitives#2034]
### Current Behavior

The library cannot test the switch of tabpanel when clicking tabitem while writing unit tests with @testing-library/react against the Tabs component.
The expected tabpanel to be displayed results still inactive.

### Expected behavior

Expected tab is active

### Reproducible example

https://github.com/radix-ui/primitives/compare/main...silversonicaxel:primitives:tabs-tests

this is the error I'm facing with the associated previously linked code
```
 FAIL  packages/react/tabs/src/Tabs.test.tsx
  given a Tab List
    with default behaviour in an uncontrolled scenario
      ✓ should have no accessibility violations in default state (227 ms)
      ✓ should check proper presence of all tablist entities (17 ms)
      ✕ should show the proper tabpanel accordingly to click navigation (20 ms)
    with default behaviour in a controlled scenario
      ✓ should have no accessibility violations in default state (42 ms)
      ✓ should check proper presence of all tablist entities (11 ms)
      ✕ should show the proper tabpanel accordingly to click navigation (12 ms)

  ● given a Tab List › with default behaviour in an uncontrolled scenario › should show the proper tabpanel accordingly to click navigation

    expect(element).toHaveAttribute("data-state", "inactive") // element.getAttribute("data-state") === "inactive"

    Expected the element to have attribute:
      data-state="inactive"
    Received:
      data-state="active"

      54 |
      55 |       expect(panel1).toHaveAttribute('data-state', 'inactive');
    > 56 |       expect(panel2).toHaveAttribute('data-state', 'inactive');
         |                      ^
      57 |       expect(panel3).toHaveAttribute('data-state', 'active');
      58 |       expect(panel4).toHaveAttribute('data-state', 'inactive');
      59 |     });

      at Object.<anonymous> (packages/react/tabs/src/Tabs.test.tsx:56:22)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)

  ● given a Tab List › with default behaviour in a controlled scenario › should show the proper tabpanel accordingly to click navigation

    expect(element).toHaveAttribute("data-state", "inactive") // element.getAttribute("data-state") === "inactive"

    Expected the element to have attribute:
      data-state="inactive"
    Received:
      data-state="active"

      109 |
      110 |       expect(panel1).toHaveAttribute('data-state', 'inactive');
    > 111 |       expect(panel2).toHaveAttribute('data-state', 'inactive');
          |                      ^
      112 |       expect(panel3).toHaveAttribute('data-state', 'active');
      113 |       expect(panel4).toHaveAttribute('data-state', 'inactive');
      114 |     });

      at Object.<anonymous> (packages/react/tabs/src/Tabs.test.tsx:111:22)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 4 passed, 6 total
Snapshots:   0 total
Time:        0.642 s, estimated 1 s
Ran all test suites related to changed files.

```

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | Tabs        | 1.0.3        |
| React            | n/a     |  18.0.0 or 18.2.0       |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |    macOS        | Monterey | Ventura        |

**Comment by benoitgrelard** [comment]
Have you tried using `userEvent` rather than `fireEvent`?

**Comment by silversonicaxel** [comment]
hello @benoitgrelard ,
I tried with userEvent.click from version `"@testing-library/user-event": "^14.1.0",` but it still behaves as with `fireEvent`

**Comment by benoitgrelard** [comment]
Unfortunately this is the issue with unit tests and not running tests in real browsers.
Inevitably you end up having to write your tests by considering the implementation.
In this case, it's most likely because the implementation doesn't use `onClick` but rather `onMouseDown` and `onKeyDown`, so perhaps try some of those events.

**Comment by silversonicaxel** [comment]
I also created a PR to add the few tests I wrote, it is not complete, but it is better than nothing. 
FYI @benoitgrelard

**Comment by ravirajput99** [comment]
I have also faced this issue, I tried userEvent click and mouseUp, mouseDown. In browser clicking tabs changes the focus and and visibility but in test it doesn't changes the focus even after clicking not sure what's happening?
