### ISSUE TITLE
CONTRIBUTING: Can't use Yarn install

### ISSUE THREAD

**Issue by sandrina-p** [radix-ui/primitives#2159]
Hi team,

I was following the [contributing](https://github.com/radix-ui/primitives/blob/main/.github/CONTRIBUTING.md), but after the fork, the `yarn install` fails on my macbook. In each package installation, it says ` YN0001: │ Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close` and my mac starts to get really slow. Here's a [screenshot](https://github.com/radix-ui/primitives/assets/14869087/4ed00e30-2636-470a-b884-6f5e91a84ba6).

my MacBook:
- macos 12.6.5 (16' from 2019)
- yarn 3.0.1
- node 18.14.0 

I also tried to use GitHub codespaces, but on `yarn install` I get an error `Internal Error: Cannot redefine settings "changesetBaseRefs"` [screenshot](https://github.com/radix-ui/primitives/assets/14869087/66411332-d8ed-49f6-aa76-02962394e3b9).

What am I missing? Thanks :)

**Comment by sandrina-p** [comment]
Update: I noticed the nvmrc file which requires node 14.6.0 I installed it, and now got a different error: [screenshot](https://github.com/radix-ui/primitives/assets/14869087/96b0d816-5a59-4fb5-ad13-586d1c8e0c8d)

```
Internal Error: Unable to deserialize cloned data due to invalid or unsupported version.
    at Object.deserialize (v8.js:262:7)
    at Fe.restoreInstallState (/Users/bob/Documents/radix-ui-primitives/.yarn/releases/yarn-3.0.1.cjs:309:854)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Dp.execute (/Users/bob/Documents/radix-ui-primitives/.yarn/releases/yarn-3.0.1.cjs:348:14577)
    at async Dp.validateAndExecute (/Users/bob/Documents/radix-ui-primitives/.yarn/releases/yarn-3.0.1.cjs:197:620)
    at async ts.run (/Users/bob/Documents/radix-ui-primitives/.yarn/releases/yarn-3.0.1.cjs:211:1846)
    at async ts.runExit (/Users/bob/Documents/radix-ui-primitives/.yarn/releases/yarn-3.0.1.cjs:211:2013)
    at async i (/Users/bob/Documents/radix-ui-primitives/.yarn/releases/yarn-3.0.1.cjs:310:12327)
    at async r (/Users/bob/Documents/radix-ui-primitives/.yarn/releases/yarn-3.0.1.cjs:310:10567)
```

Do you have any other suggestion?

**Comment by benoitgrelard** [comment]
Weird… I don't really know what's going on here.
This is what I have on my side:

```bash
› node --version
v16.17.0

› yarn --version
3.0.1
```

**Comment by sandrina-p** [comment]
Ah ah! That did the trick. I changed the node to 16.7.0 and it worked!

my suggestion: highlight the expected node version in the contributing file. Update the `.nvmrc` from 14.6.0 to 16.17.0. Here's the PR https://github.com/radix-ui/primitives/pull/2160 :)

**Comment by sagorzaii** [comment]
Hello. I'm still getting this error even though my node is `v16.17.0`. How to fix it?

```
$ yarn install
Internal Error: Unable to deserialize cloned data due to invalid or unsupported version.
    at Object.deserialize (node:v8:366:7)
    at Fe.restoreInstallState (C:\Users\tians\Documents\devsandbox\radix_ui_primitives\.yarn\releases\yarn-3.0.1.cjs:309:854)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Dp.execute (C:\Users\tians\Documents\devsandbox\radix_ui_primitives\.yarn\releases\yarn-3.0.1.cjs:348:14577)
    at async Dp.validateAndExecute (C:\Users\tians\Documents\devsandbox\radix_ui_primitives\.yarn\releases\yarn-3.0.1.cjs:197:620)
    at async ts.run (C:\Users\tians\Documents\devsandbox\radix_ui_primitives\.yarn\releases\yarn-3.0.1.cjs:211:1846)
    at async ts.runExit (C:\Users\tians\Documents\devsandbox\radix_ui_primitives\.yarn\releases\yarn-3.0.1.cjs:211:2013)
    at async i (C:\Users\tians\Documents\devsandbox\radix_ui_primitives\.yarn\releases\yarn-3.0.1.cjs:310:12327)
    at async r (C:\Users\tians\Documents\devsandbox\radix_ui_primitives\.yarn\releases\yarn-3.0.1.cjs:310:10567)
```

**Comment by sandrina-p** [comment]
@sagorzaii have you tried to delete `.yarn/cache` and try again?

**Comment by sagorzaii** [comment]
@sandrina-p hey thanks for replying!
Yup, tried it. But, it's still returning the same error.

**Comment by sandrina-p** [comment]
Hmmm, What about `node_modules` and `yarn/install-state.gh`? Besides that I don't know :/

**Comment by ealexhaywood** [comment]
Deleting `yarn/install-state.gh` fixed it for me
