### ISSUE TITLE
React testing library - "test was not wrapped in act"

### ISSUE THREAD

**Issue by jd-carroll** [radix-ui/primitives#2619]
Not sure where to start on this one, but I am getting persistent console messages warning that:
```shell
    Warning: An update to Checkbox inside a test was not wrapped in act(...).
```

I have a pretty straight forward implementation with Jest & react-testing library and I am attempting to render a test with state updates. I cannot seem to get rid of any these warnings despite different configurations with `act()` & `render()`. I've also attempted adding a `waitFor` with a timeout, but still doesn't seem to help. (Full stacktrace below)

**Has anyone seen and / or solved for this "`test was not wrapped in act(...)`"?** Is this a Jest issue or a react-testing library issue (misconfiguration)?

Note: The behavior jest/react is complaining about is not in our code. This seems to clearly be coming from something in the primitives library. In the example below the stacktrace is from `Checkbox`. But I receive the same errors from `Presence` and maybe some others as well.

Any support appreciated, not really sure where to start on this one.

<details>

<summary>Fullstack trace</summary>

```shell
  console.error
    Warning: An update to Checkbox inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at /Users/me/develop/project/project-client-workbench/node_modules/@radix-ui/react-checkbox/dist/packages/react/checkbox/src/Checkbox.tsx:45:7
        at span
        at /Users/me/develop/project/project-client-workbench/node_modules/@radix-ui/themes/src/components/checkbox.tsx:19:66
        at span
        at /Users/me/develop/project/project-client-workbench/node_modules/@radix-ui/react-slot/dist/packages/react/slot/src/Slot.tsx:61:11
        at /Users/me/develop/project/project-client-workbench/node_modules/@radix-ui/react-slot/dist/packages/react/slot/src/Slot.tsx:13:11
        at commitMutationEffectsOnFiber (/Users/me/develop/project/project-client-workbench/node_modules/react-dom/cjs/react-dom.development.js:24293:9)
        at div
        at /Users/me/develop/project/project-client-workbench/node_modules/@radix-ui/themes/src/components/flex.tsx:25:66
        at CheckField (/Users/me/develop/project/project-client-workbench/packages/client-components/formik/CheckField.tsx:18:30)
        at form
        at /Users/me/develop/project/project-client-workbench/node_modules/formik/src/Form.tsx:19:13
        at Step1AccountDetailsForm (/Users/me/develop/project/project-client-workbench/features/client-sign-up/src/components/step1/Step1AccountDetailsForm.tsx:30:3)
        at Formik (/Users/me/develop/project/project-client-workbench/node_modules/formik/src/Formik.tsx:1004:21)
        at Step1AccountDetailsFormProvider (/Users/me/develop/project/project-client-workbench/features/client-sign-up/src/components/step1/Step1AccountDetailsFormProvider.tsx:11:3)
        at Step1AccountDetails (/Users/me/develop/project/project-client-workbench/features/client-sign-up/src/components/step1/Step1AccountDetails.tsx:25:39)
        at SignUpSessionProvider (/Users/me/develop/project/project-client-workbench/features/client-sign-up/src/contexts/SignUpSession/SignUpSessionProvider.tsx:49:41)
        at Provider (/Users/me/develop/project/project-client-workbench/node_modules/react-redux/lib/components/Provider.js:19:3)
        at Wrapper (/Users/me/develop/project/project-client-workbench/packages/client-redux/src/utils/test-utils.tsx:39:22)
        at TestableReduxStore (/Users/me/develop/project/project-client-workbench/packages/client-testable-utils/lib/testable/TestableReduxStore.tsx:11:32)
        at PlatformMonitoringMockProvider (/Users/me/develop/project/project-client-workbench/packages/client-core/services/platform-monitoring/platform-monitoring-context.mock.tsx:28:50)
        at ThemeConsumerResolver (/Users/me/develop/project/project-client-workbench/packages/client-theme/src/extended-theme.tsx:183:71)
        at div
        at /Users/me/develop/project/project-client-workbench/node_modules/@radix-ui/themes/src/theme.tsx:153:25
        at /Users/me/develop/project/project-client-workbench/node_modules/@radix-ui/themes/src/theme.tsx:38:25
        at /Users/me/develop/project/project-client-workbench/packages/client-theme/src/extended-theme.tsx:149:25
        at /Users/me/develop/project/project-client-workbench/packages/client-theme/src/extended-theme.tsx:64:25
        at Object.<anonymous>.exports.ThemeProvider (/Users/me/develop/project/project-client-workbench/node_modules/next-themes/dist/index.js:37:111)
        at SystemThemeProvider (/Users/me/develop/project/project-client-workbench/packages/client-theme/src/components/system-theme-provider.tsx:7:39)
        at div
        at ClientThemeProvider (/Users/me/develop/project/project-client-workbench/packages/client-testable-utils/lib/testable/ClientThemeProvider.tsx:20:39)
        at NextSearchParamsProvider (/Users/me/develop/project/project-client-workbench/packages/client-testable-utils/lib/testable/next-navigation/NextSearchParamsProvider.tsx:11:3)
        at NextPathProviders (/Users/me/develop/project/project-client-workbench/packages/client-testable-utils/lib/testable/next-navigation/NextPathProviders.tsx:84:37)
        at NavigationRouterProvider (/Users/me/develop/project/project-client-workbench/packages/client-testable-utils/lib/testable/next-navigation/NextRouterProvider.tsx:93:44)
        at NextNavigationProviders (/Users/me/develop/project/project-client-workbench/packages/client-testable-utils/lib/testable/next-navigation/NextNavigationProviders.tsx:17:43)
        at TestableComponent (/Users/me/develop/project/project-client-workbench/packages/client-testable-utils/lib/TestableComponent.tsx:12:37)
        at Provider (/Users/me/develop/project/project-client-workbench/node_modules/react-redux/lib/components/Provider.js:19:3)
        at Wrapper (/Users/me/develop/project/project-client-workbench/packages/client-redux/src/utils/test-utils.tsx:39:22)
        at TestableReduxStore (/Users/me/develop/project/project-client-workbench/packages/client-testable-utils/lib/testable/TestableReduxStore.tsx:11:32)
        at PlatformMonitoringMockProvider (/Users/me/develop/project/project-client-workbench/packages/client-core/services/platform-monitoring/platform-monitoring-context.mock.tsx:28:50)
        at ThemeConsumerResolver (/Users/me/develop/project/project-client-workbench/packages/client-theme/src/extended-theme.tsx:183:71)
        at div
        at /Users/me/develop/project/project-client-workbench/node_modules/@radix-ui/themes/src/theme.tsx:153:25
        at /Users/me/develop/project/project-client-workbench/node_modules/@radix-ui/themes/src/theme.tsx:56:17
        at $cc45c1b701a63adc$export$c760c09fdd558351 (/Users/me/develop/project/project-client-workbench/node_modules/@radix-ui/react-direction/dist/packages/react/direction/src/Direction.tsx:15:11)
        at Provider (/Users/me/develop/project/project-client-workbench/node_modules/@radix-ui/react-context/dist/packages/react/context/src/createContext.tsx:58:15)
        at $c34afbc43c90cc6f$export$f78649fb9ca566b8 (/Users/me/develop/project/project-client-workbench/node_modules/@radix-ui/react-tooltip/dist/packages/react/tooltip/src/Tooltip.tsx:69:5)
        at /Users/me/develop/project/project-client-workbench/node_modules/@radix-ui/themes/src/theme.tsx:38:25
        at /Users/me/develop/project/project-client-workbench/packages/client-theme/src/extended-theme.tsx:149:25
        at BreakpointsProvider (/Users/me/develop/project/project-client-workbench/packages/client-theme/src/helpers/breakpoints-provider.tsx:10:68)
        at /Users/me/develop/project/project-client-workbench/packages/client-theme/src/extended-theme.tsx:76:17
        at /Users/me/develop/project/project-client-workbench/packages/client-theme/src/extended-theme.tsx:64:25
        at m (/Users/me/develop/project/project-client-workbench/node_modules/next-themes/dist/index.js:2:127)
        at Object.<anonymous>.exports.ThemeProvider (/Users/me/develop/project/project-client-workbench/node_modules/next-themes/dist/index.js:37:111)
        at SystemThemeProvider (/Users/me/develop/project/project-client-workbench/packages/client-theme/src/components/system-theme-provider.tsx:7:39)
        at div
        at ClientThemeProvider (/Users/me/develop/project/project-client-workbench/packages/client-testable-utils/lib/testable/ClientThemeProvider.tsx:20:39)
        at NextSearchParamsProvider (/Users/me/develop/project/project-client-workbench/packages/client-testable-utils/lib/testable/next-navigation/NextSearchParamsProvider.tsx:11:3)
        at NextPathProviders (/Users/me/develop/project/project-client-workbench/packages/client-testable-utils/lib/testable/next-navigation/NextPathProviders.tsx:84:37)
        at NavigationRouterProvider (/Users/me/develop/project/project-client-workbench/packages/client-testable-utils/lib/testable/next-navigation/NextRouterProvider.tsx:93:44)
        at NextNavigationProviders (/Users/me/develop/project/project-client-workbench/packages/client-testable-utils/lib/testable/next-navigation/NextNavigationProviders.tsx:17:43)
        at TestableComponent (/Users/me/develop/project/project-client-workbench/packages/client-testable-utils/lib/TestableComponent.tsx:12:37)

      at printWarning (../../node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (../../node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at warnIfUpdatesNotWrappedWithActDEV (../../node_modules/react-dom/cjs/react-dom.development.js:27589:9)
      at scheduleUpdateOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:25508:5)
      at setButton (../../node_modules/react-dom/cjs/react-dom.development.js:17527:7)
      at ref (../../node_modules/@radix-ui/react-checkbox/dist/packages/react/checkbox/src/Checkbox.tsx:56:66)
      at setRef (../../node_modules/@radix-ui/react-compose-refs/dist/packages/react/compose-refs/src/composeRefs.tsx:11:5)
      at forEach (../../node_modules/@radix-ui/react-compose-refs/dist/packages/react/compose-refs/src/composeRefs.tsx:22:45)
          at Array.forEach (<anonymous>)
      at ../../node_modules/@radix-ui/react-compose-refs/dist/packages/react/compose-refs/src/composeRefs.tsx:22:28
      at safelyDetachRef (../../node_modules/react-dom/cjs/react-dom.development.js:22913:20)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24003:11)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24018:11)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24018:11)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24018:11)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24018:11)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24170:9)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at recursivelyTraverseDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23989:5)
      at commitDeletionEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24118:9)
      at commitDeletionEffects (../../node_modules/react-dom/cjs/react-dom.development.js:23976:5)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24259:9)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24293:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24576:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24293:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24576:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24293:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24293:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24293:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24576:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24293:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24293:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24346:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24576:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24293:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24293:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24576:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24293:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24293:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24293:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24293:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24346:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24293:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24576:9)
      at recursivelyTraverseMutationEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24273:7)
      at commitMutationEffectsOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24293:9)
```
</details>

**Comment by jd-carroll** [comment]
Linking a related issue:
https://github.com/testing-library/user-event/issues/1114
